2018-10-01 13:08:51,154 ERROR: Exception on /reset_password_request [GET] [in /Users/e83/Documents/Code/anaconda3/lib/python3.5/site-packages/flask/app.py:1587]
Traceback (most recent call last):
  File "/Users/e83/Documents/Code/anaconda3/lib/python3.5/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/e83/Documents/Code/anaconda3/lib/python3.5/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/e83/Documents/Code/anaconda3/lib/python3.5/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/e83/Documents/Code/anaconda3/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/e83/Documents/Code/anaconda3/lib/python3.5/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/e83/Documents/Code/anaconda3/lib/python3.5/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/e83/Documents/GitHub/LearningProjects/Flask_Mega_Tutorial/ Chapter10/microblog/app/routes.py", line 102, in reset_password_request
    title='Reset Password', form=form)
  File "/Users/e83/Documents/Code/anaconda3/lib/python3.5/site-packages/flask/templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/e83/Documents/Code/anaconda3/lib/python3.5/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/e83/Documents/Code/anaconda3/lib/python3.5/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/e83/Documents/Code/anaconda3/lib/python3.5/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/e83/Documents/Code/anaconda3/lib/python3.5/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/e83/Documents/Code/anaconda3/lib/python3.5/site-packages/flask/templating.py", line 57, in get_source
    return self._get_source_fast(environment, template)
  File "/Users/e83/Documents/Code/anaconda3/lib/python3.5/site-packages/flask/templating.py", line 85, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: reset_password_request.html
2018-10-01 13:09:43,364 ERROR: Exception on /reset_password_request [GET] [in /Users/e83/Documents/Code/anaconda3/lib/python3.5/site-packages/flask/app.py:1587]
Traceback (most recent call last):
  File "/Users/e83/Documents/Code/anaconda3/lib/python3.5/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/e83/Documents/Code/anaconda3/lib/python3.5/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/e83/Documents/Code/anaconda3/lib/python3.5/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/e83/Documents/Code/anaconda3/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/e83/Documents/Code/anaconda3/lib/python3.5/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/e83/Documents/Code/anaconda3/lib/python3.5/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/e83/Documents/GitHub/LearningProjects/Flask_Mega_Tutorial/ Chapter10/microblog/app/routes.py", line 102, in reset_password_request
    title='Reset Password', form=form)
  File "/Users/e83/Documents/Code/anaconda3/lib/python3.5/site-packages/flask/templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/e83/Documents/Code/anaconda3/lib/python3.5/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/e83/Documents/Code/anaconda3/lib/python3.5/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/e83/Documents/Code/anaconda3/lib/python3.5/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/e83/Documents/Code/anaconda3/lib/python3.5/site-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/Users/e83/Documents/Code/anaconda3/lib/python3.5/site-packages/jinja2/environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/Users/e83/Documents/Code/anaconda3/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/e83/Documents/Code/anaconda3/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/e83/Documents/GitHub/LearningProjects/Flask_Mega_Tutorial/ Chapter10/microblog/app/templates/reset_password_request.html", line 3, in template
    {% block_content %}
  File "/Users/e83/Documents/Code/anaconda3/lib/python3.5/site-packages/jinja2/environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/Users/e83/Documents/Code/anaconda3/lib/python3.5/site-packages/jinja2/parser.py", line 901, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/Users/e83/Documents/Code/anaconda3/lib/python3.5/site-packages/jinja2/parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "/Users/e83/Documents/Code/anaconda3/lib/python3.5/site-packages/jinja2/parser.py", line 144, in parse_statement
    self.fail_unknown_tag(token.value, token.lineno)
  File "/Users/e83/Documents/Code/anaconda3/lib/python3.5/site-packages/jinja2/parser.py", line 97, in fail_unknown_tag
    return self._fail_ut_eof(name, self._end_token_stack, lineno)
  File "/Users/e83/Documents/Code/anaconda3/lib/python3.5/site-packages/jinja2/parser.py", line 90, in _fail_ut_eof
    self.fail(' '.join(message), lineno)
  File "/Users/e83/Documents/Code/anaconda3/lib/python3.5/site-packages/jinja2/parser.py", line 59, in fail
    raise exc(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'block_content'.
2018-10-01 13:10:07,324 INFO: Microblog startup [in /Users/e83/Documents/GitHub/LearningProjects/Flask_Mega_Tutorial/ Chapter10/microblog/app/__init__.py:59]
2018-10-01 13:10:15,602 ERROR: Exception on /reset_password_request [POST] [in /Users/e83/Documents/Code/anaconda3/lib/python3.5/site-packages/flask/app.py:1587]
Traceback (most recent call last):
  File "/Users/e83/Documents/Code/anaconda3/lib/python3.5/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/e83/Documents/Code/anaconda3/lib/python3.5/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/e83/Documents/Code/anaconda3/lib/python3.5/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/e83/Documents/Code/anaconda3/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/e83/Documents/Code/anaconda3/lib/python3.5/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/e83/Documents/Code/anaconda3/lib/python3.5/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/e83/Documents/GitHub/LearningProjects/Flask_Mega_Tutorial/ Chapter10/microblog/app/routes.py", line 98, in reset_password_request
    send_password_reset_email(user)
TypeError: send_password_reset_email() takes 0 positional arguments but 1 was given
2018-10-01 13:12:40,770 INFO: Microblog startup [in /Users/e83/Documents/GitHub/LearningProjects/Flask_Mega_Tutorial/ Chapter10/microblog/app/__init__.py:59]
2018-10-01 13:12:52,707 ERROR: Exception on /reset_password_request [POST] [in /Users/e83/Documents/Code/anaconda3/lib/python3.5/site-packages/flask/app.py:1587]
Traceback (most recent call last):
  File "/Users/e83/Documents/Code/anaconda3/lib/python3.5/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/e83/Documents/Code/anaconda3/lib/python3.5/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/e83/Documents/Code/anaconda3/lib/python3.5/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/e83/Documents/Code/anaconda3/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/e83/Documents/Code/anaconda3/lib/python3.5/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/e83/Documents/Code/anaconda3/lib/python3.5/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/e83/Documents/GitHub/LearningProjects/Flask_Mega_Tutorial/ Chapter10/microblog/app/routes.py", line 98, in reset_password_request
    send_password_reset_email(user)
  File "/Users/e83/Documents/GitHub/LearningProjects/Flask_Mega_Tutorial/ Chapter10/microblog/app/email.py", line 14, in send_password_reset_email
    sender=app.config['ADMINS'][0],
NameError: name 'app' is not defined
