2018-10-01 09:27:54,081 ERROR: Exception on / [GET] [in /Users/e83/Documents/Code/anaconda3/lib/python3.5/site-packages/flask/app.py:1587]
Traceback (most recent call last):
  File "/Users/e83/Documents/Code/anaconda3/lib/python3.5/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/e83/Documents/Code/anaconda3/lib/python3.5/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/e83/Documents/Code/anaconda3/lib/python3.5/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/e83/Documents/Code/anaconda3/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/e83/Documents/Code/anaconda3/lib/python3.5/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/e83/Documents/Code/anaconda3/lib/python3.5/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/e83/Documents/Code/anaconda3/lib/python3.5/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/e83/Documents/GitHub/LearningProjects/Flask_Mega_Tutorial/ Chapter9/microblog/app/routes.py", line 24, in index
    page, instance_of_Flask.config(['POSTS_PER_PAGE']), False)
TypeError: 'Config' object is not callable
2018-10-01 09:28:19,517 INFO: Microblog startup [in /Users/e83/Documents/GitHub/LearningProjects/Flask_Mega_Tutorial/ Chapter9/microblog/app/__init__.py:55]
2018-10-01 09:28:22,264 ERROR: Exception on / [GET] [in /Users/e83/Documents/Code/anaconda3/lib/python3.5/site-packages/flask/app.py:1587]
Traceback (most recent call last):
  File "/Users/e83/Documents/Code/anaconda3/lib/python3.5/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/e83/Documents/Code/anaconda3/lib/python3.5/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/e83/Documents/Code/anaconda3/lib/python3.5/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/e83/Documents/Code/anaconda3/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/e83/Documents/Code/anaconda3/lib/python3.5/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/e83/Documents/Code/anaconda3/lib/python3.5/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/e83/Documents/Code/anaconda3/lib/python3.5/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/e83/Documents/GitHub/LearningProjects/Flask_Mega_Tutorial/ Chapter9/microblog/app/routes.py", line 25, in index
    return render_template('index.html', title='Home Page', form=form, posts=posts)
  File "/Users/e83/Documents/Code/anaconda3/lib/python3.5/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/Users/e83/Documents/Code/anaconda3/lib/python3.5/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/Users/e83/Documents/Code/anaconda3/lib/python3.5/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/e83/Documents/Code/anaconda3/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/e83/Documents/Code/anaconda3/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/e83/Documents/GitHub/LearningProjects/Flask_Mega_Tutorial/ Chapter9/microblog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/e83/Documents/GitHub/LearningProjects/Flask_Mega_Tutorial/ Chapter9/microblog/app/templates/base.html", line 31, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/e83/Documents/GitHub/LearningProjects/Flask_Mega_Tutorial/ Chapter9/microblog/app/templates/index.html", line 18, in block "content"
    {% for post in posts %}
TypeError: 'Pagination' object is not iterable
2018-10-01 09:28:23,473 ERROR: Exception on / [GET] [in /Users/e83/Documents/Code/anaconda3/lib/python3.5/site-packages/flask/app.py:1587]
Traceback (most recent call last):
  File "/Users/e83/Documents/Code/anaconda3/lib/python3.5/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/e83/Documents/Code/anaconda3/lib/python3.5/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/e83/Documents/Code/anaconda3/lib/python3.5/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/e83/Documents/Code/anaconda3/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/e83/Documents/Code/anaconda3/lib/python3.5/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/e83/Documents/Code/anaconda3/lib/python3.5/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/e83/Documents/Code/anaconda3/lib/python3.5/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/e83/Documents/GitHub/LearningProjects/Flask_Mega_Tutorial/ Chapter9/microblog/app/routes.py", line 25, in index
    return render_template('index.html', title='Home Page', form=form, posts=posts)
  File "/Users/e83/Documents/Code/anaconda3/lib/python3.5/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/Users/e83/Documents/Code/anaconda3/lib/python3.5/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/Users/e83/Documents/Code/anaconda3/lib/python3.5/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/e83/Documents/Code/anaconda3/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/e83/Documents/Code/anaconda3/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/e83/Documents/GitHub/LearningProjects/Flask_Mega_Tutorial/ Chapter9/microblog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/e83/Documents/GitHub/LearningProjects/Flask_Mega_Tutorial/ Chapter9/microblog/app/templates/base.html", line 31, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/e83/Documents/GitHub/LearningProjects/Flask_Mega_Tutorial/ Chapter9/microblog/app/templates/index.html", line 18, in block "content"
    {% for post in posts %}
TypeError: 'Pagination' object is not iterable
